import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { Routes, Route, Link } from 'react-router-dom';
import BookList from './features/books/BookList';
import BookDashboard from './features/books/BookDashboard';
import WorldBuilder from './features/world/WorldBuilder';
import PageEditor from './features/pages/PageEditor';
import VersionTimeline from './features/pages/VersionTimeline';
import DiffView from './features/pages/DiffView';
import ToastHost from './components/ToastHost';
import FloatingGPTButton from './components/FloatingGPTButton';
import GPTOverlay from './components/GPTOverlay';
import GPTChatPanel from './components/GPTChatPanel';
import ReactDOM from 'react-dom';
const Placeholder = ({ title }) => (_jsxs("div", { className: "p-4", children: [_jsx("h2", { className: "text-xl font-semibold mb-2", children: title }), _jsx("p", { className: "text-sm text-text-dim", children: "\uAD6C\uD604 \uC608\uC815..." }), _jsx(Link, { to: "/", className: "text-primary underline text-sm", children: "\uCC45 \uBAA9\uB85D\uC73C\uB85C" })] }));
const App = () => {
    const [open, setOpen] = React.useState(false);
    return (_jsxs("div", { className: "min-h-screen bg-bg text-text", children: [_jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(BookList, {}) }), _jsx(Route, { path: "/books/:bookId", element: _jsx(BookDashboard, {}) }), _jsx(Route, { path: "/books/:bookId/world", element: _jsx(WorldBuilder, {}) }), _jsx(Route, { path: "/books/:bookId/pages/:pageIndex", element: _jsx(PageEditor, {}) }), _jsx(Route, { path: "/books/:bookId/pages/:pageIndex/versions", element: _jsx(VersionTimeline, {}) }), _jsx(Route, { path: "/books/:bookId/pages/:pageIndex/diff/:versionId", element: _jsx(DiffView, {}) }), _jsx(Route, { path: "*", element: _jsx(Placeholder, { title: "Not Found" }) })] }), _jsx(ToastHost, {}), _jsx(FloatingGPTButton, { onOpen: () => setOpen(true) }), ReactDOM.createPortal(_jsx(GPTOverlay, { open: open, onClose: () => setOpen(false), children: _jsx(GPTChatPanel, {}) }), document.body)] }));
};
export default App;
